; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
core_dir = c:/dev/pio

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.arduino.usb_mode = 0
board_build.arduino.usb_cdc_on_boot = 0
build_unflags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_MODE=2
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DMIDI_SEND_MODE=2
build_flags = 
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=0
lib_deps = 
	adafruit/Adafruit GFX Library @ ^1.12.3
	adafruit/Adafruit SH110X @ ^2.1.11
  	adafruit/Adafruit SSD1306@^2.5.15
  	felis/USB-Host-Shield-20 @ ^1.6.0
board_build.sdkconfig = sdkconfig.esp32-s3-devkitc-1
